### ISSUE TITLE
CSE stock exchange not working ..!

### ISSUE THREAD

**Issue by khyrulAlam** [khyrulAlam/DSE-CSE-Market-Update#1]
Chittagong stock exchange website change their html markup. 

![three](https://user-images.githubusercontent.com/26439209/70171150-54491e80-16f8-11ea-94c1-285626644166.PNG)
![one](https://user-images.githubusercontent.com/26439209/70171228-7cd11880-16f8-11ea-9a0c-6a6da4e53b78.PNG)

**Comment by simongomes** [comment]
I see, they changed their markup!
